- 👋 Hi, I’m @Marvel-Data 
- 👀 I’m interested in Data Science and analytics
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 You can reach me through marvel.bolaji@gmail.com or through my Twitter account, link in my profile.
